package br.com.projetoLes.dominio;

public enum STATUS_PEDIDO {

	
	EM_PROCESSAMENTO, 
	PAGAMENTO_REALIZADO, 
	EM_TRANSPORTE, 
	ENTREGA_REALIZADA, 
	TROCA_SOLICITADA, 
	TROCA_AUTORIZADA, 
	TROCA_REJEITADA, 
	TROCA_ACEITA, 
	TROCA_EFETUADA, 
	CANCELAMENTO_SOLICITADO, 
	CANCELAMENTO_REJEITADO, 
	CANCELAMENTO_ACEITO, 
	CANCELAMENTO_EFETUADO
	
}
